### PR TITLE
[WIP] Fix ht interface

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR is for fixing the hashtable interface. **I also changes the public interface.**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@neithernut I'm guess this is ready, please review.

**Comment by neithernut** [comment]
ACK. The reason the CI fails is fixed in PR #106 btw.

**Comment by matthiasbeyer** [comment]
Fixed the suggested stuff. I removed the `typdef` for the hash function type and embedded it into the cfg type. (I also ran a short `ack rs_hash_function` over the source to be sure it doesn't get used).

**Comment by matthiasbeyer** [comment]
Actually, this is a PR into `implement-ht`, but I guess I will (manually) merge this into master. Keeps things less complicated to some point.

**Pull request closed without merging**
