### PR TITLE
Check for the existence of a node before inserting a new one

### PR DESCRIPTION
**Pull request by neithernut**
This PR fixes an potential issue.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
"an potential" issue?

**Comment by neithernut** [comment]
Well, it's a real issue, which was, however, not observed yet.

**Comment by matthiasbeyer** [comment]
And _what issue_?

**Comment by neithernut** [comment]
Distortion of the tree by insertion of multiple nodes with the same hash/key.

**Pull request merged**
