### PR TITLE
Add build env speedup

### PR DESCRIPTION
**Pull request by neithernut**
This PR will hopefully help solving issue #199.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
As the build does build the paper _while_ building the sources. Wouldn't it be better to build the source with `-j3` and _afterwards_ the paper with `-j3`?

**Comment by neithernut** [comment]
If we want to look at the Travis CI output on a regular basis, this would indeed be the better option.
However, we use local checks, either through hooks or by manually trying to compile. For this case, the additional speedup of doing everything in _one_ make call is preferable imho.

**Comment by neithernut** [comment]
I split up the make calls.

**Comment by matthiasbeyer** [comment]
Feel free to rebase now.

**Comment by neithernut** [comment]
Done.

**Pull request merged**
