### PR TITLE
Added implementation for ht_ndel()

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Solves #136 .

### CODE REVIEW

**Comment by neithernut** [comment]
ACK.

**Comment by matthiasbeyer** [comment]
Failing because `avl_ndel()` (which is used by `ht_ndel()`) is not implemented yet. Setting this one on hold.

**Comment by neithernut** [comment]
Please rebase, resolve merge conflicts.

**Comment by neithernut** [comment]
Do you want to make some parameters const now? Or do you plan on doing this in another PR?

**Comment by neithernut** [comment]
May now be merged.

**Pull request merged**
