### PR TITLE
Fix: CONSTPOW_TWO() macro type

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by TheNeikos** [comment]
ACK

**Comment by neithernut** [comment]
When merging this, we have to change every "call" of this macro: we have to cast the operand to `size_t`.

**Comment by matthiasbeyer** [comment]
Then it is better if we do not merge this, right?

**Comment by TheNeikos** [comment]
I think it is only used for ht->sizeexp which is _already_ a `size_t`

**Comment by matthiasbeyer** [comment]
So I'll close this now.

**Pull request closed without merging**
