### PR TITLE
Added .travis.yml file

### LINKED ISSUE #18: Add travis-ci integration.
Add travis-ci integration.

This relates to #1 and #16 .

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR adds the `.travis.yml` file and closes #18 therefor.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@neithernut it says the build fails, the travis configuration should be right now. Can you fix this and create a PR onto _this_ branch that fixes the build?

**Comment by matthiasbeyer** [comment]
@neithernut Q: Should we add some Email/IRC notification on build? [Travis supports this](http://docs.travis-ci.com/user/notifications/) and I would be pleased to see some notifications per mail and IRC!

I would then add some configurations to the file for printing to our IRC channel at the local IRC server or freenode, which you prefer! I would use our local one... 

I also wouldn't if my mail address shows up in the config, as it is already on my github profile...  :-) But maybe others don't like this, especially @manuelmessner ! You could add your email adresses on your own then...

**Comment by neithernut** [comment]
Ah... old cmake installations do not know about add_compile_flags()
I'll resort to a fallback, but the pull-request will be to the main repo since this affects the `CMakeLists.txt` rather than the Travis CI file.

**Comment by matthiasbeyer** [comment]
:+1:

**Comment by matthiasbeyer** [comment]
For documentation: #44 is the attempt to solve the issue named above.

Build passed afterwards. Merged.

**Pull request merged**
