### PR TITLE
Implement ht tests

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Targets #101

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@neithernut We have a _really_ interesting problem here.

Try to run the tests. The tests fail for the following values:
- Number of inserted values: 1000
- Number of buckets in the hashtable: 2^2 (4) up to 2^8 (256).

So the idea comes up that it works while the number of buckets is greater than the half of the number of inserted values (it does _not_ fail for 512 buckets and 1024 buckets).

**But** it also does not fail when having 4 buckets and inserting 100 values. Obviously 4 < (100/2). So this seems to be a _really_ strange bug. Maybe _you_ can trace it, but I am unable to find it and neither does @TheNeikos  .

---

Another good point: I insert the _last_ value as first, so it fails when inserting `1000`, which is the `first` value inserted!

**Comment by neithernut** [comment]
I'll look into this as soon as I can spare the time.

**Comment by matthiasbeyer** [comment]
nah, @TheNeikos and I fixed this, I guess (can't remember, ... I'm still a bit tired, sorry...)

**Comment by matthiasbeyer** [comment]
@neithernut , @TheNeikos SYN

**Comment by TheNeikos** [comment]
ACK-SYN

**Comment by neithernut** [comment]
ACK.

**Pull request merged**
