### PR TITLE
Header for attribute macros

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR adds an util/attributes.h header file for utility attribute macros.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@neithernut , @theneikos, @manuelmessner : Please review.

**Comment by neithernut** [comment]
Is this written by hand? If not, please name the source in either the file or in the commit message.

**Comment by matthiasbeyer** [comment]
It is written by hand completely.

**Comment by neithernut** [comment]
In this case: ack.

**Pull request merged**
