### PR TITLE
Adapt avl del

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Solves #109 , relates #108 .

### CODE REVIEW

**Comment by neithernut** [comment]
We also need a `void* data` argument to identify the item to delete in the linked list.

**Comment by matthiasbeyer** [comment]
Isn't this covered by the predicate already?

**Comment by neithernut** [comment]
What predicate? you removed the predicate.
Anyways, the whole point of having `_del` and `_ndel` was to have a specialized, fast function for removal of _one_ element, fow which you have to provide a comparable, and a function to remove any element for which a predicate is true.

**Comment by neithernut** [comment]
Relates to issue #103.

**Comment by matthiasbeyer** [comment]
I meant the _predicate_ as the _cfg_, sorry for messing these two up here.

**Comment by neithernut** [comment]
In this case it's _not_ covered by the predicate.

**Comment by matthiasbeyer** [comment]
Ah, now I understand: You meant a comparator with the `void*`, which is passed to the comparator function as second argument? I will add this.

**Comment by neithernut** [comment]
ACK.

**Comment by matthiasbeyer** [comment]
Rebased. Waiting on CI.

**Pull request merged**
