### PR TITLE
Use the C11-standart for builds

### PR DESCRIPTION
**Pull request by neithernut**
This PR adds the C-standart to use to the Compiler flags for the project.

### CODE REVIEW

**Comment by neithernut** [comment]
Argh.... old compilers!

**Comment by matthiasbeyer** [comment]
You actually want to use C11 ???

I would stick to C99!

**Comment by neithernut** [comment]
That's what you get for using ubuntu^^

**Comment by neithernut** [comment]
Using C11 would have the benefit of having locks without the use for explicit pthread-usage.

**Comment by neithernut** [comment]
Maybe this can be fixed by editing the Travis-CI setup. I'll have a look at it this evening. (away now)

**Comment by matthiasbeyer** [comment]
Ok.

**Comment by neithernut** [comment]
The job's done for the gcc suite.
When including a clang-build in the future, the compiler's installation/update should be performed based on what run is currently performed.

**Comment by TheNeikos** [comment]
Just to nitpick: It's standard, but good work! :+1:

**Comment by matthiasbeyer** [comment]
So it seems that you guys want C11. So, I'll merge this now.

**Pull request merged**
