### PR TITLE
Add build env doc

### PR DESCRIPTION
**Pull request by neithernut**
This PR adds a target "doc" which may be used to build the doxygen documentation.

### CODE REVIEW

**Comment by neithernut** [comment]
This solves issue #40.

**Comment by matthiasbeyer** [comment]
`cmake . && make doc` doesn't build the docs for me. Maybe I did something wrong here?

**Comment by neithernut** [comment]
I would have to look at your working directory, or your CMakeCache.txt files.
Note that `make doc` only builds the doxygen documentation (doc/gen), `make paper` builds the paper.

**Comment by neithernut** [comment]
@matthiasbeyer: any new info? The issue related to this PR blocks a miliestone which is due today.

**Comment by matthiasbeyer** [comment]
`make doc` still does nothing for me, I don't know what is wrong with it.

What I did:

``` bash
git clean -fd
cmake .
make doc
```

But the `doc/gen` subdir is empty afterwards.

---

even 

``` bash
rm -r *.cmake CMakeCache.txt CMakeFiles/ Makefile
cmake .
make doc
```

doesn't build the doc. Ideas?

**Comment by neithernut** [comment]
Could you `tar` the directory and send it via e-mail?

**Comment by matthiasbeyer** [comment]
Done. Please throw away after you're finished.

**Comment by neithernut** [comment]
Mh... turns out it doesn't work here, either. I must have broken something...

**Comment by neithernut** [comment]
I had a condition screwed up which was added afterwards. Turned out the old target was still in the buffer somewhere. Please test and ACK.

**Comment by matthiasbeyer** [comment]
How about test and merge? :-P

**Pull request merged**
