### PR TITLE
[WIP] Add testing for linked list implementation

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR adds tests for the linked list implementation.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@neithernut Can you please add the build setup.

We use the `check` testing framework here.

**Comment by neithernut** [comment]
Yep, I'll have a look at it. You may open another issue for that.
The test might be expanded btw.
ACK for now.

**Comment by matthiasbeyer** [comment]
I'll not merge this without build setup and I would prefer the build setup patches go into this PR. Too much PRs and Issues create too much noise in the repository, somewhere we have to keep things short and compact.

**Comment by neithernut** [comment]
k, I'll add a note on how to include this test after I've brought up the infrastructure.

**Comment by matthiasbeyer** [comment]
Any updates on this? I would like to write the tests as soon as possible!

**Comment by neithernut** [comment]
I focused on the paper since the milestone is due today. However, I'll assign more time to doing this PR's prequisites. Hopefully, I'll be done with it in 24h max.

**Comment by neithernut** [comment]
I will need to build _something_, else the PR will not be very meaningul.
I recommend merging at least `tests/tests.c` with the one test stripped. After that is done I can push a setup.
(As a temporary work-around I started a private integration branch on this machine)

**Comment by matthiasbeyer** [comment]
I will create a PR for the basic testing infrastructure.

**Comment by matthiasbeyer** [comment]
@neithernut Thanks for your testing build setup stuff, this seems to work now as expected. I will add more tests for the LL implementation from now on (in this PR).

**Comment by matthiasbeyer** [comment]
@neithernut btw, there is a commit in this PR which fixes the build main file as well. I will not put this into a seperate PR, as this would again cause noise in the repo which is kind-of unneccessary.

**Comment by neithernut** [comment]
Why did you discard the NULL terminated list of tests?

**Comment by matthiasbeyer** [comment]
Because it was buggy somehow.

**Comment by matthiasbeyer** [comment]
Any suggestions what I also could test?

**Comment by matthiasbeyer** [comment]
@neithernut Can you have a look at the travis log and interpret that message for me?

**Comment by neithernut** [comment]
Some function does not exist: `undefined reference to 'ck_assert_ptr_eq'`

**Comment by matthiasbeyer** [comment]
For documentation:

On Ubuntu (travis-ci ubuntu: 12.04) only version 0.9.8 if "check" is available. A possible fix _could_ be installing another version from the backports, but it _seems_ that it is not available in the backports of Ubuntu 12.04 (I'm not an Shitbuntu guy, so I don't know how to search them properly...).

---

I'm not happy with the fact that the build servers at travis use Ubuntu, but I cannot change it. So we try to live with the fact here. It is against our philosophy, but hey ... we need a CI and travis is easy to setup and configure when it comes to the `travis.yml` thing. We should try to avoid trouble with the OS, so we can focus on important things without having this bullshit from Canonical in our way.

---

Anyways, using functionality from pre-v0.9.8 and v0.9.8. of check should be enough.

**Comment by matthiasbeyer** [comment]
Relates to #16 btw.

**Comment by matthiasbeyer** [comment]
I'm a bit confused that there is _so_ little test output. I mean... why do I name the tests? I assumed at least some output like "Test foobar: sucess" or something.

@neithernut can you please review _really_ carefully, also the output from travis, if the tests actually ran?

---

edit: I did, too, but I'm insecure about this one :-P

**Comment by neithernut** [comment]
It sais `Running suite(s): Linkedlist`, so i assume it will list all the tests it's running.
I also assume that it will list all the tests that failed.
Maybe there's some option you can enable to have more output?

**Comment by matthiasbeyer** [comment]
Ahh, yes! I will add the appropriate flag.

**Comment by neithernut** [comment]
Now that's a little more output.

**Comment by neithernut** [comment]
ACK for merge.

**Pull request merged**
