### PR TITLE
Convert comments

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR converts the comments to be ISO-C90 compatible.

### CODE REVIEW

**Comment by neithernut** [comment]
ISO-C90? Why bother? Every reasonable compiler knows (at-least) C99.

**Comment by matthiasbeyer** [comment]
Because for me, the current build setup prints a number of warnings because of this comment style!

This is an approach to fix the code, an approach for fixing this with the build setup would be appropriate, too. But I like the comment style much more, it is more C-like, I think.

But well, that's personal taste...

**Comment by neithernut** [comment]
Fixing the build-setup is, indeed more reasonable. Await a PR from me

**Comment by matthiasbeyer** [comment]
Ok. I will close this unmerged.

**Pull request closed without merging**
