### PR TITLE
r_set type implementation

### PR DESCRIPTION
**Pull request by matthiasbeyer**
No related issue.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Blocks: #164 , #165 , #166 , #167 , #168 , #169 , #170 , #171 , #172 , #173 , #174 , #175 , #176

**Comment by neithernut** [comment]
ACK.

**Comment by matthiasbeyer** [comment]
Even if this pulls the `ht.h` header into the public interface? I don't know how to solve this properly, so I assume this is fine the way it is?

**Comment by neithernut** [comment]
`set.c` is not part of the public interface.

**Comment by matthiasbeyer** [comment]
I'm sorry. I messed things up. I'll merge right now.

**Pull request merged**
