### PR TITLE
Add drone support

### PR DESCRIPTION
**Pull request by TheNeikos**
This adds drone support for this repository.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
relates to #204

**Comment by matthiasbeyer** [comment]
@TheNeikos I guess you can remove the latest commit, as IRC notification seems to be unavailable by now

**Comment by matthiasbeyer** [comment]
@neithernut SYN

**Comment by neithernut** [comment]
ACK.

**Comment by neithernut** [comment]
Would suggest merge after PRs #211, #216 and #221 are merged.

**Pull request merged**
