### PR TITLE
Run astyle on the codebase

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
This wouldn't be necessary if all of us would use the pre-commit hook.

**Comment by neithernut** [comment]
Astyle fucks up labels.

**Comment by matthiasbeyer** [comment]
This will be closed. Reviews should be done much more carefully due to this. Style is important!

**Comment by matthiasbeyer** [comment]
@neithernut I'd welcome a PR for removing astyle from the pre-commit hook.

**Pull request closed without merging**
