### PR TITLE
Add paper when to rebalance

### PR DESCRIPTION
**Pull request by neithernut**
This PR adds a description of a rebalancing algorithm, which was already implemented in PR #74.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Does the CI at this point already cover the paper? (I'm too sick and tired to review carefully)

**Comment by neithernut** [comment]
Yep.

**Comment by matthiasbeyer** [comment]
Do you want to cleanup the history?

**Comment by neithernut** [comment]
I cleaned the history before adding the PR.

**Pull request merged**
