### PR TITLE
Add ll_is_empty

### PR DESCRIPTION
**Pull request by neithernut**
This PR solves issue #143.

### CODE REVIEW

**Comment by neithernut** [comment]
Before merging: I'll add a little change to an avl function before...

**Comment by neithernut** [comment]
Done. Ready for merge.

**Comment by matthiasbeyer** [comment]
The code for this function could be implemented right in the header and marked as `inline`. But well, I don't care much about this at this moment.

Waiting for CI.

**Comment by neithernut** [comment]
With this small library we can afford putting _all_ the implementation into the source files.
Hail LTO! (still has to be activated, though...)

**Pull request merged**
