### PR TITLE
Expand ll tests

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Expands the ll tests by inserting more assertions and adding a test for the new empty checker function.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@TheNeikos please review and ack.

**Comment by neithernut** [comment]
I'm not a friend on fiddeling with internas of data structures.
The tests should _only_ use the interface of a datastructure!

**Comment by matthiasbeyer** [comment]
But how do you test the interface of the datastructure when only using the interface itself?

**Comment by neithernut** [comment]
By observing the result of operations.
Example: if you insert an item successfully, it should be able to delete it. If you try to delete the same item twice or an item which is not in the list, the function should return false.
Also: checking for internas is bad testing because
- internas may change
- you tend to write tests based on implementation details, possibly lacking other aspects.

Have a look at what @TheNeikos did in the AVL tests (PR #133).

**Comment by matthiasbeyer** [comment]
I fully understand your point. But how do you guarantee that the deletion algorithms works here?

**Comment by neithernut** [comment]
E.g. try to find the element. If you found it _before_ the deletion and you do not find it _after_ the deletion, `ll_del()` behaves as expected.

**Comment by TheNeikos** [comment]
I agree with that.

A test called `ll_find_test` can test beyond that, but should focus on find. It is crucial to make sure that everything works together! That way I cannot change `ll_del` _without_ making sure it always works as intended. With TDD you spec out your interface (and implicitely the usage) so that you can be sure it actually looks right beforehand.

**Comment by matthiasbeyer** [comment]
Travis failed with:

```
2: /home/travis/build/matthiasbeyer/libreset/tests/ll/ll_test.c:21:F:Inserting:test_ll_insert_data:0: Assertion '1==ll_delete(ll, &data, &cfg_int)' failed: 1==1, ll_delete(ll, &data, &cfg_int)==1
```

Can someone please explain this to me? Why the hell does it fail?

**Comment by neithernut** [comment]
Works on this machine...
Can you somehow trigger a rebuild?

**Comment by matthiasbeyer** [comment]
@neithernut started rebuild. Travis seems to be under heavy load atm, so this could take a while...

**Comment by neithernut** [comment]
So now I have _two_ machines on which this test passes...
Something _must_ be wrong with the CI.

**Comment by matthiasbeyer** [comment]
@neithernut , @TheNeikos seems to be solved by the latest commit. The problem was (as for #156) the `ck_assert_int_eq()` macro.

**Comment by neithernut** [comment]
May now be rebased and merged.

**Comment by matthiasbeyer** [comment]
No need for rebase here, merge?

**Comment by neithernut** [comment]
Yep.

**Pull request merged**
