### PR TITLE
Added test main file

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR adds a main file for the testing setup, containing test execution.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Relates #58 , #89

**Comment by neithernut** [comment]
ACK, obviously.

**Comment by matthiasbeyer** [comment]
mhm... I don't know if this compiles or anything... but yeah, that's obvious that you cannot the setup before setting it up completely.

So I'll merge.

**Comment by matthiasbeyer** [comment]
Obviously, this was not reviewed. But now it is in the master.

There are at least two problems with the code which result in a compile-error. We are in pre-1.0, but this stuff really should not happen! Not even in pre-1.0!

**Comment by neithernut** [comment]
In this case, it's a bootstrapping problem. Someone _should_ have tried to build the file by hand, but that's a missed opportunity now.
You may either push a fix or wait for me to fix it as soon as it becomes neccessary.

**Comment by matthiasbeyer** [comment]
The latter should be enough.

**Comment by neithernut** [comment]
Done, see PR #89.

**Pull request merged**
